Fix configure so that we do timing on Windows
git-svn-id: http://svn.research.cc.gatech.edu/kaos/cercs_env/trunk@13 8ba6a8b9-845b-0410-94f0-974be2f5df47

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6763,13 +6763,15 @@ if test $ac_cv_func_gethrtime = yes; then
     TIMING=hrtime
 fi
 
-if test "$host_os" = linux-gnu; then
-   case $host_cpu in
-   i*86)
-    TIMING=linux_x86
+case $host_os in
+   linux-gnu | cygwin | mingw32)
+	case $GCC,$host_cpu in
+	yes,i*86)
+	    TIMING=gcc_x86
+	    ;;
+	esac
     ;;
-    esac
-fi
+esac
 
 if test -z "$TIMING"; then
     TIMING=gettimeofday
@@ -6868,7 +6870,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:6871: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:6873: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -7044,7 +7046,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:7047: error: ambiguous option: $1
+    { { echo "$as_me:7049: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -7068,12 +7070,12 @@ Try \`$0 --help' for more information." >&2;}
   'config.h' ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:7071: error: unrecognized option: $1
+  -*) { { echo "$as_me:7073: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:7076: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:7078: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -7335,7 +7337,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:7338: creating $ac_file" >&5
+    { echo "$as_me:7340: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -7353,7 +7355,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7356: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7358: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7366,7 +7368,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7369: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7371: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7427,7 +7429,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:7430: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:7432: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -7438,7 +7440,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7441: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7443: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7451,7 +7453,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7454: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7456: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7568,7 +7570,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:7571: $ac_file is unchanged" >&5
+      { echo "$as_me:7573: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
